// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using new_wr_api.Data;

#nullable disable

namespace new_wr_api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231012044214_update_newColumn")]
    partial class update_newColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("new_wr_api.Data.AspNetRoles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("new_wr_api.Data.AspNetUsers", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("new_wr_api.Data.BieuMauSoHai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("MuaKhoBaoCao")
                        .HasColumnType("float");

                    b.Property<double?>("MuaKhoKyTruoc")
                        .HasColumnType("float");

                    b.Property<double?>("MuaKhoThayDoi")
                        .HasColumnType("float");

                    b.Property<double?>("MuaMuaBaoCao")
                        .HasColumnType("float");

                    b.Property<double?>("MuaMuaKyTruoc")
                        .HasColumnType("float");

                    b.Property<double?>("MuaMuaThayDoi")
                        .HasColumnType("float");

                    b.Property<double?>("MuaNamBaoCao")
                        .HasColumnType("float");

                    b.Property<double?>("MuaNamKyTruoc")
                        .HasColumnType("float");

                    b.Property<double?>("MuaNamThayDoi")
                        .HasColumnType("float");

                    b.Property<string>("TenTram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiKyQuanTrac")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BieuMauSoHai");
                });

            modelBuilder.Entity("new_wr_api.Data.CT_HangMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChuThich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<int?>("IdCT")
                        .HasColumnType("int");

                    b.Property<int?>("IdTangChuaNuoc")
                        .HasColumnType("int");

                    b.Property<string>("TaiKhoanSua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHangMuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianSua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("VịTriHangMuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("X")
                        .HasColumnType("float");

                    b.Property<double?>("Y")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdCT");

                    b.ToTable("CT_HangMuc");
                });

            modelBuilder.Entity("new_wr_api.Data.CT_Loai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChuThich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<int?>("IdCha")
                        .HasColumnType("int");

                    b.Property<string>("MaLoaiCT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanSua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoaiCT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianSua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CT_Loai");
                });

            modelBuilder.Entity("new_wr_api.Data.CT_ThongSo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("CaoTrinhCong")
                        .HasColumnType("float");

                    b.Property<double?>("CaoTrinhDap")
                        .HasColumnType("float");

                    b.Property<double?>("CapCT")
                        .HasColumnType("float");

                    b.Property<double?>("ChieuCaoDap")
                        .HasColumnType("float");

                    b.Property<double?>("ChieuDaiCong")
                        .HasColumnType("float");

                    b.Property<double?>("ChieuDaiDap")
                        .HasColumnType("float");

                    b.Property<double?>("ChieuRongCong")
                        .HasColumnType("float");

                    b.Property<double?>("ChieuSauDoanThuNuocDen")
                        .HasColumnType("float");

                    b.Property<double?>("ChieuSauDoanThuNuocTu")
                        .HasColumnType("float");

                    b.Property<double?>("CongSuatBom")
                        .HasColumnType("float");

                    b.Property<double?>("CongSuatDamBao")
                        .HasColumnType("float");

                    b.Property<double?>("CongSuatLM")
                        .HasColumnType("float");

                    b.Property<bool?>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<double?>("DienTichLuuVuc")
                        .HasColumnType("float");

                    b.Property<double?>("DienTichTuoiThietKe")
                        .HasColumnType("float");

                    b.Property<double?>("DienTichTuoiThucTe")
                        .HasColumnType("float");

                    b.Property<double?>("DungTichChet")
                        .HasColumnType("float");

                    b.Property<double?>("DungTichHuuIch")
                        .HasColumnType("float");

                    b.Property<double?>("DungTichToanBo")
                        .HasColumnType("float");

                    b.Property<double?>("HBeHut")
                        .HasColumnType("float");

                    b.Property<double?>("HDatOngLocDen")
                        .HasColumnType("float");

                    b.Property<double?>("HDatOngLocTu")
                        .HasColumnType("float");

                    b.Property<double?>("HGiengKT")
                        .HasColumnType("float");

                    b.Property<double?>("HHaLuu")
                        .HasColumnType("float");

                    b.Property<double?>("HHaThap")
                        .HasColumnType("float");

                    b.Property<double?>("HThuongLuu")
                        .HasColumnType("float");

                    b.Property<double?>("Hgieng")
                        .HasColumnType("float");

                    b.Property<double?>("Hlu")
                        .HasColumnType("float");

                    b.Property<double?>("Hmax")
                        .HasColumnType("float");

                    b.Property<double?>("Hmin")
                        .HasColumnType("float");

                    b.Property<double?>("HtoiThieu")
                        .HasColumnType("float");

                    b.Property<int?>("IdCT")
                        .HasColumnType("int");

                    b.Property<int?>("IdHangMucCT")
                        .HasColumnType("int");

                    b.Property<double?>("KichThuocCong")
                        .HasColumnType("float");

                    b.Property<double?>("KqKf")
                        .HasColumnType("float");

                    b.Property<double?>("LuongNuocKT")
                        .HasColumnType("float");

                    b.Property<double?>("MNC")
                        .HasColumnType("float");

                    b.Property<double?>("MNDBT")
                        .HasColumnType("float");

                    b.Property<double?>("MNLKT")
                        .HasColumnType("float");

                    b.Property<double?>("MNLTK")
                        .HasColumnType("float");

                    b.Property<double?>("MuaTrungBinhNam")
                        .HasColumnType("float");

                    b.Property<double?>("MucNuocDong")
                        .HasColumnType("float");

                    b.Property<double?>("MucNuocTinh")
                        .HasColumnType("float");

                    b.Property<double?>("PhuongThucKT")
                        .HasColumnType("float");

                    b.Property<double?>("QBomLonNhat")
                        .HasColumnType("float");

                    b.Property<double?>("QBomThietKe")
                        .HasColumnType("float");

                    b.Property<double?>("QDamBao")
                        .HasColumnType("float");

                    b.Property<double?>("QKTCapNuocSinhHoat")
                        .HasColumnType("float");

                    b.Property<double?>("QKTLonNhat")
                        .HasColumnType("float");

                    b.Property<double?>("QKhaiThac")
                        .HasColumnType("float");

                    b.Property<double?>("QLonNhatTruocLu")
                        .HasColumnType("float");

                    b.Property<double?>("QMaxKT")
                        .HasColumnType("float");

                    b.Property<double?>("QMaxXaThai")
                        .HasColumnType("float");

                    b.Property<double?>("QThietKe")
                        .HasColumnType("float");

                    b.Property<double?>("QThucTe")
                        .HasColumnType("float");

                    b.Property<double?>("QTrungBinhNam")
                        .HasColumnType("float");

                    b.Property<double?>("QXaThai")
                        .HasColumnType("float");

                    b.Property<double?>("QXaThaiLonNhat")
                        .HasColumnType("float");

                    b.Property<double?>("QXaThaiTB")
                        .HasColumnType("float");

                    b.Property<double?>("QXaTran")
                        .HasColumnType("float");

                    b.Property<double?>("QmaxNM")
                        .HasColumnType("float");

                    b.Property<double?>("Qtt")
                        .HasColumnType("float");

                    b.Property<double?>("SoLuongMayBom")
                        .HasColumnType("float");

                    b.Property<string>("TaiKhoanSua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TangChuaNuocKT")
                        .HasColumnType("float");

                    b.Property<double?>("ThoiGianBomLonNhat")
                        .HasColumnType("float");

                    b.Property<double?>("ThoiGianBomNhoNhat")
                        .HasColumnType("float");

                    b.Property<double?>("ThoiGianBomTB")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ThoiGianSua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdCT")
                        .IsUnique()
                        .HasFilter("[IdCT] IS NOT NULL");

                    b.HasIndex("IdHangMucCT")
                        .IsUnique()
                        .HasFilter("[IdHangMucCT] IS NOT NULL");

                    b.ToTable("CT_ThongSo");
                });

            modelBuilder.Entity("new_wr_api.Data.CT_ThongTin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CHeDoXT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheDoKT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuThich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<double?>("DungTichTT")
                        .HasColumnType("float");

                    b.Property<double?>("HHaLuuTT")
                        .HasColumnType("float");

                    b.Property<double?>("HThuongLuuTT")
                        .HasColumnType("float");

                    b.Property<string>("IdHuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdLoaiCT")
                        .HasColumnType("int");

                    b.Property<int?>("IdLuuVuc")
                        .HasColumnType("int");

                    b.Property<int?>("IdSong")
                        .HasColumnType("int");

                    b.Property<int?>("IdTangChuaNuoc")
                        .HasColumnType("int");

                    b.Property<int?>("IdTieuLuuVuc")
                        .HasColumnType("int");

                    b.Property<string>("IdXa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KhoiLuongCacHangMucTD")
                        .HasColumnType("int");

                    b.Property<int?>("Loi")
                        .HasColumnType("int");

                    b.Property<string>("MaCT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MatKetNoi")
                        .HasColumnType("int");

                    b.Property<string>("MucDichHNK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDichhKT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDichhTD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NamBatDauVanHanh")
                        .HasColumnType("int");

                    b.Property<string>("NguonNuocKT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguonNuocXT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhuongThucKT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhuongThucXT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QKTThietKe")
                        .HasColumnType("int");

                    b.Property<int?>("QKTThucTe")
                        .HasColumnType("int");

                    b.Property<double?>("QMaxTT")
                        .HasColumnType("float");

                    b.Property<double?>("QMinTT")
                        .HasColumnType("float");

                    b.Property<double?>("QXaMaxTT")
                        .HasColumnType("float");

                    b.Property<string>("QuyMoHNK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuongGieng")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongGiengKT")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongGiengQT")
                        .HasColumnType("int");

                    b.Property<string>("TaiKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanSua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiGianHNK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiGianKT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianSua")
                        .HasColumnType("datetime2");

                    b.Property<double?>("ThoiGianTT")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThoiGianXD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViTriCT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViTriXT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("X")
                        .HasColumnType("float");

                    b.Property<double?>("Y")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdLoaiCT");

                    b.ToTable("CT_ThongTin");
                });

            modelBuilder.Entity("new_wr_api.Data.Dashboards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PermitAccess")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Dashboards");
                });

            modelBuilder.Entity("new_wr_api.Data.DonViHC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapHanhChinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("IdHuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdXa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanSua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenXa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianSua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DonViHC");
                });

            modelBuilder.Entity("new_wr_api.Data.Functions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermitCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermitName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Functions");
                });

            modelBuilder.Entity("new_wr_api.Data.GP_Loai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLoaiGP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanSua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoaiGP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianSua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GP_Loai");
                });

            modelBuilder.Entity("new_wr_api.Data.GP_TCQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdGP")
                        .HasColumnType("int");

                    b.Property<int>("IdTCQ")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdGP");

                    b.HasIndex("IdTCQ");

                    b.ToTable("GP_TCQ");
                });

            modelBuilder.Entity("new_wr_api.Data.GP_ThongTin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoQuanCapPhep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DaBiThuHoi")
                        .HasColumnType("bit");

                    b.Property<bool?>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("FileDonXinCP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileGiayPhep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileGiayToLienQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCT")
                        .HasColumnType("int");

                    b.Property<int?>("IdCon")
                        .HasColumnType("int");

                    b.Property<int?>("IdLoaiGP")
                        .HasColumnType("int");

                    b.Property<int?>("IdTCCN")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCoHieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoGP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanSua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenGP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianSua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThoiHan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCT");

                    b.HasIndex("IdLoaiGP");

                    b.HasIndex("IdTCCN");

                    b.ToTable("GP_ThongTin");
                });

            modelBuilder.Entity("new_wr_api.Data.GS_DuLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConstructionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeviceStatus")
                        .HasColumnType("int");

                    b.Property<string>("ParameterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("GS_DuLieu");
                });

            modelBuilder.Entity("new_wr_api.Data.GS_TaiKhoanTruyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CameraLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Port")
                        .HasColumnType("int");

                    b.Property<string>("Protocol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingDirectory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GS_TaiKhoanTruyen");
                });

            modelBuilder.Entity("new_wr_api.Data.LuuVucSong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChuGiai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<int?>("NgayBatDau")
                        .HasColumnType("int");

                    b.Property<int?>("NgayKetThuc")
                        .HasColumnType("int");

                    b.Property<string>("TaiKhoanSua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLVS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianSua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ViTriQT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LuuVucSong");
                });

            modelBuilder.Entity("new_wr_api.Data.Permissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DashboardId")
                        .HasColumnType("int");

                    b.Property<string>("FunctionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FunctionId")
                        .HasColumnType("int");

                    b.Property<string>("FunctionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("new_wr_api.Data.RoleDashboards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DashboardId")
                        .HasColumnType("int");

                    b.Property<string>("FileControl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PermitAccess")
                        .HasColumnType("bit");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleDashboards");
                });

            modelBuilder.Entity("new_wr_api.Data.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChuGiai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<int?>("IdHuyen")
                        .HasColumnType("int");

                    b.Property<int?>("IdLuuVuc")
                        .HasColumnType("int");

                    b.Property<int?>("IdXa")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartRiverId")
                        .HasColumnType("int");

                    b.Property<double?>("Qtt")
                        .HasColumnType("float");

                    b.Property<string>("TaiKhoanSua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianSua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<double?>("X")
                        .HasColumnType("float");

                    b.Property<double?>("Y")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Song");
                });

            modelBuilder.Entity("new_wr_api.Data.TCQ_ThongTin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoQuanCP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("FilePDF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCon")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoQDTCQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanSua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianSua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<double?>("TongTienCQ")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TCQ_ThongTin");
                });

            modelBuilder.Entity("new_wr_api.Data.TLN_NuocDuoiDat_SoLuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ChieuSauPhanBoDen")
                        .HasColumnType("float");

                    b.Property<double?>("ChieuSauPhanBoTu")
                        .HasColumnType("float");

                    b.Property<double?>("DienTichPhanBo")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("HTBBaoCao")
                        .HasColumnType("float");

                    b.Property<double?>("HTBKyTruoc")
                        .HasColumnType("float");

                    b.Property<double?>("HTBThayDoi")
                        .HasColumnType("float");

                    b.Property<double?>("HmaxBaoCao")
                        .HasColumnType("float");

                    b.Property<double?>("HmaxKyTruoc")
                        .HasColumnType("float");

                    b.Property<double?>("HmaxThayDoi")
                        .HasColumnType("float");

                    b.Property<double?>("HminBaoCao")
                        .HasColumnType("float");

                    b.Property<double?>("HminKyTruoc")
                        .HasColumnType("float");

                    b.Property<double?>("HminThayDoi")
                        .HasColumnType("float");

                    b.Property<int?>("IdTangChuaNuoc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TLN_NuocDuoiDat_SoLuong");
                });

            modelBuilder.Entity("new_wr_api.Data.TLN_NuocDuoiDat_TongLuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdTangChuaNuoc")
                        .HasColumnType("int");

                    b.Property<double?>("NuocMan_DienTichPhanBo")
                        .HasColumnType("float");

                    b.Property<int?>("NuocMan_IdHuyen")
                        .HasColumnType("int");

                    b.Property<int?>("NuocMan_IdXa")
                        .HasColumnType("int");

                    b.Property<double?>("NuocMan_TruLuong")
                        .HasColumnType("float");

                    b.Property<float?>("NuocNgot_DienTichPhanBo")
                        .HasColumnType("real");

                    b.Property<int?>("NuocNgot_IdHuyen")
                        .HasColumnType("int");

                    b.Property<int?>("NuocNgot_IdXa")
                        .HasColumnType("int");

                    b.Property<double?>("NuocNgot_TLCoTheKhaiThac")
                        .HasColumnType("float");

                    b.Property<double?>("NuocNgot_TLTiemNang")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TLN_NuocDuoiDat_TongLuong");
                });

            modelBuilder.Entity("new_wr_api.Data.TLN_NuocMat_ChatLuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("BOD5Max")
                        .HasColumnType("float");

                    b.Property<double?>("BOD5Min")
                        .HasColumnType("float");

                    b.Property<double?>("CODMax")
                        .HasColumnType("float");

                    b.Property<double?>("CODMin")
                        .HasColumnType("float");

                    b.Property<double?>("DOMax")
                        .HasColumnType("float");

                    b.Property<double?>("DOMin")
                        .HasColumnType("float");

                    b.Property<int?>("GiaTriWQI")
                        .HasColumnType("int");

                    b.Property<int?>("IdHuyen")
                        .HasColumnType("int");

                    b.Property<int?>("IdLuuVucSong")
                        .HasColumnType("int");

                    b.Property<int?>("IdTinh")
                        .HasColumnType("int");

                    b.Property<int?>("IdXa")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TLN_NuocMat_ChatLuong");
                });

            modelBuilder.Entity("new_wr_api.Data.TLN_NuocMat_SoLuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChayRa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ChieuDai")
                        .HasColumnType("float");

                    b.Property<int?>("IdHuyenCuoiSong")
                        .HasColumnType("int");

                    b.Property<int?>("IdHuyenDauSong")
                        .HasColumnType("int");

                    b.Property<int?>("IdSong")
                        .HasColumnType("int");

                    b.Property<int?>("IdXaCuoiSong")
                        .HasColumnType("int");

                    b.Property<int?>("IdXaDauSong")
                        .HasColumnType("int");

                    b.Property<double?>("XCuoiSong")
                        .HasColumnType("float");

                    b.Property<double?>("XDauSong")
                        .HasColumnType("float");

                    b.Property<double?>("YCuoiSong")
                        .HasColumnType("float");

                    b.Property<double?>("YDauSong")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TLN_NuocMat_SoLuong");
                });

            modelBuilder.Entity("new_wr_api.Data.TLN_NuocMat_TongLuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdHuyen")
                        .HasColumnType("int");

                    b.Property<int?>("IdLuuVucSong")
                        .HasColumnType("int");

                    b.Property<int?>("IdXa")
                        .HasColumnType("int");

                    b.Property<int?>("Nam")
                        .HasColumnType("int");

                    b.Property<double?>("Thang1")
                        .HasColumnType("float");

                    b.Property<double?>("Thang10")
                        .HasColumnType("float");

                    b.Property<double?>("Thang11")
                        .HasColumnType("float");

                    b.Property<double?>("Thang12")
                        .HasColumnType("float");

                    b.Property<double?>("Thang2")
                        .HasColumnType("float");

                    b.Property<double?>("Thang3")
                        .HasColumnType("float");

                    b.Property<double?>("Thang4")
                        .HasColumnType("float");

                    b.Property<double?>("Thang5")
                        .HasColumnType("float");

                    b.Property<double?>("Thang6")
                        .HasColumnType("float");

                    b.Property<double?>("Thang7")
                        .HasColumnType("float");

                    b.Property<double?>("Thang8")
                        .HasColumnType("float");

                    b.Property<double?>("Thang9")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TLN_NuocMat_TongLuong");
                });

            modelBuilder.Entity("new_wr_api.Data.TLN_NuocMua_TongLuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdTram")
                        .HasColumnType("int");

                    b.Property<double?>("Thang1")
                        .HasColumnType("float");

                    b.Property<double?>("Thang10")
                        .HasColumnType("float");

                    b.Property<double?>("Thang11")
                        .HasColumnType("float");

                    b.Property<double?>("Thang12")
                        .HasColumnType("float");

                    b.Property<double?>("Thang2")
                        .HasColumnType("float");

                    b.Property<double?>("Thang3")
                        .HasColumnType("float");

                    b.Property<double?>("Thang4")
                        .HasColumnType("float");

                    b.Property<double?>("Thang5")
                        .HasColumnType("float");

                    b.Property<double?>("Thang6")
                        .HasColumnType("float");

                    b.Property<double?>("Thang7")
                        .HasColumnType("float");

                    b.Property<double?>("Thang8")
                        .HasColumnType("float");

                    b.Property<double?>("Thang9")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TLN_NuocMua_TongLuong");
                });

            modelBuilder.Entity("new_wr_api.Data.TangChuaNuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("KyHieuTCN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuongGiengQT")
                        .HasColumnType("int");

                    b.Property<string>("TaiKhoanSua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTCN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianSua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TangChuaNuoc");
                });

            modelBuilder.Entity("new_wr_api.Data.TieuVungLuuVuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChuGiai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<int?>("IdLuuVuc")
                        .HasColumnType("int");

                    b.Property<string>("TaiKhoanSua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianSua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuVungQuyHoach")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TieuVungLuuVuc");
                });

            modelBuilder.Entity("new_wr_api.Data.ToChuc_CaNhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiamDoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiDaiDienPhapLuat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiDuocUyQuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanSua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTCCN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianSua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ToChuc_CaNhan");
                });

            modelBuilder.Entity("new_wr_api.Data.Tram_LoaiTram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChuThich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<int?>("IdCha")
                        .HasColumnType("int");

                    b.Property<string>("MaLoaiCT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanSua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoaiCT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianSua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tram_LoaiTram");
                });

            modelBuilder.Entity("new_wr_api.Data.Tram_ThongTin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CameraLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuThich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChiTram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoSoHoatDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoSoThanhLap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdHuyen")
                        .HasColumnType("int");

                    b.Property<int?>("IdLoaiTram")
                        .HasColumnType("int");

                    b.Property<int?>("IdXa")
                        .HasColumnType("int");

                    b.Property<string>("MaTram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NgayBatDau")
                        .HasColumnType("int");

                    b.Property<int?>("NgayKetThuc")
                        .HasColumnType("int");

                    b.Property<bool?>("OnlineStatus")
                        .HasColumnType("bit");

                    b.Property<string>("TaiKhoanSua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianSua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<double?>("X")
                        .HasColumnType("float");

                    b.Property<double?>("Y")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Tram_ThongTin");
                });

            modelBuilder.Entity("new_wr_api.Data.UserDashboards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DashboardId")
                        .HasColumnType("int");

                    b.Property<string>("FileControl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PermitAccess")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserDashboards");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("new_wr_api.Data.AspNetRoles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("new_wr_api.Data.AspNetUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("new_wr_api.Data.AspNetUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("new_wr_api.Data.AspNetRoles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("new_wr_api.Data.AspNetUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("new_wr_api.Data.AspNetUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("new_wr_api.Data.CT_HangMuc", b =>
                {
                    b.HasOne("new_wr_api.Data.CT_ThongTin", "CongTrinh")
                        .WithMany("HangMuc")
                        .HasForeignKey("IdCT");

                    b.Navigation("CongTrinh");
                });

            modelBuilder.Entity("new_wr_api.Data.CT_ThongSo", b =>
                {
                    b.HasOne("new_wr_api.Data.CT_ThongTin", "CongTrinh")
                        .WithOne("ThongSo")
                        .HasForeignKey("new_wr_api.Data.CT_ThongSo", "IdCT");

                    b.HasOne("new_wr_api.Data.CT_HangMuc", "HangMuc")
                        .WithOne("ThongSo")
                        .HasForeignKey("new_wr_api.Data.CT_ThongSo", "IdHangMucCT");

                    b.Navigation("CongTrinh");

                    b.Navigation("HangMuc");
                });

            modelBuilder.Entity("new_wr_api.Data.CT_ThongTin", b =>
                {
                    b.HasOne("new_wr_api.Data.CT_Loai", "LoaiCT")
                        .WithMany("CongTrinh")
                        .HasForeignKey("IdLoaiCT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiCT");
                });

            modelBuilder.Entity("new_wr_api.Data.GP_TCQ", b =>
                {
                    b.HasOne("new_wr_api.Data.GP_ThongTin", "GP_ThongTin")
                        .WithMany("GP_TCQ")
                        .HasForeignKey("IdGP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("new_wr_api.Data.TCQ_ThongTin", "TCQ_ThongTin")
                        .WithMany("GP_TCQ")
                        .HasForeignKey("IdTCQ")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GP_ThongTin");

                    b.Navigation("TCQ_ThongTin");
                });

            modelBuilder.Entity("new_wr_api.Data.GP_ThongTin", b =>
                {
                    b.HasOne("new_wr_api.Data.CT_ThongTin", "CongTrinh")
                        .WithMany("GiayPhep")
                        .HasForeignKey("IdCT");

                    b.HasOne("new_wr_api.Data.GP_Loai", "LoaiGP")
                        .WithMany("GiayPhep")
                        .HasForeignKey("IdLoaiGP");

                    b.HasOne("new_wr_api.Data.ToChuc_CaNhan", "ToChuc_CaNhan")
                        .WithMany("GiayPhep")
                        .HasForeignKey("IdTCCN");

                    b.Navigation("CongTrinh");

                    b.Navigation("LoaiGP");

                    b.Navigation("ToChuc_CaNhan");
                });

            modelBuilder.Entity("new_wr_api.Data.CT_HangMuc", b =>
                {
                    b.Navigation("ThongSo");
                });

            modelBuilder.Entity("new_wr_api.Data.CT_Loai", b =>
                {
                    b.Navigation("CongTrinh");
                });

            modelBuilder.Entity("new_wr_api.Data.CT_ThongTin", b =>
                {
                    b.Navigation("GiayPhep");

                    b.Navigation("HangMuc");

                    b.Navigation("ThongSo");
                });

            modelBuilder.Entity("new_wr_api.Data.GP_Loai", b =>
                {
                    b.Navigation("GiayPhep");
                });

            modelBuilder.Entity("new_wr_api.Data.GP_ThongTin", b =>
                {
                    b.Navigation("GP_TCQ");
                });

            modelBuilder.Entity("new_wr_api.Data.TCQ_ThongTin", b =>
                {
                    b.Navigation("GP_TCQ");
                });

            modelBuilder.Entity("new_wr_api.Data.ToChuc_CaNhan", b =>
                {
                    b.Navigation("GiayPhep");
                });
#pragma warning restore 612, 618
        }
    }
}
